### ISSUE TITLE
Optional manifest element in workflow repository entries is ignored

### ISSUE THREAD

**Issue by heikomuller** [scailfin/flowserv-core#52]
The optional manifest element in workflow repository entries is currently ignored when installing templates. This raises an error forl the PIE workflow templates, for example:

```
Traceback (most recent call last):
  File "/home/heiko/bin/anaconda3/envs/flowapp/bin/flowapp", line 33, in <module>
    sys.exit(load_entry_point('flowserv-core', 'console_scripts', 'flowapp')())
  File "/home/heiko/bin/anaconda3/envs/flowapp/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/heiko/bin/anaconda3/envs/flowapp/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/heiko/bin/anaconda3/envs/flowapp/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/heiko/bin/anaconda3/envs/flowapp/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/heiko/bin/anaconda3/envs/flowapp/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/heiko/projects/scailfin/flowserv-core/flowserv/cli/app.py", line 76, in install_workflow
    app_key = install_app(
  File "/home/heiko/projects/scailfin/flowserv-core/flowserv/app.py", line 226, in install_app
    workflow = repo.create_workflow(
  File "/home/heiko/projects/scailfin/flowserv-core/flowserv/model/workflow/manager.py", line 134, in create_workflow
    manifest = WorkflowManifest.load(
  File "/home/heiko/projects/scailfin/flowserv-core/flowserv/model/workflow/manifest.py", line 191, in load
    raise err.InvalidManifestError('missing name')
flowserv.error.InvalidManifestError: missing name
```

**Comment by heikomuller** [comment]
Closed by commit 070cbe0a230f3702e404a591db13c36d23278312
